version: 2.1

executors:
  my-custom-executor:
    docker:
      - image: cimg/node:14.18.2

# Define the jobs we want to run for this project
jobs:
  build:
    executor: my-custom-executor
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}-<< pipeline.id >>
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-build-<< pipeline.id >>
      - run: npm ci
      - run:
          name: compiling to javascript
          command: npm run build
      - save_cache:
          paths:
            - ~/tmp/node_modules
          key: node-{{ .Branch }}-{{ checksum "package-lock.json" }}-<< pipeline.id >>
      - save_cache:
          paths:
            - ~/tmp/dist
          key: node-{{ .Branch }}-build-<< pipeline.id >>
      - store_artifacts:
          path: ~/tmp/dist
          destination: artifact-dist
  lint:
    executor: my-custom-executor
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}-<< pipeline.id >>
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-build-<< pipeline.id >>
      - run:
          name: linting
          command: npm run eslint
  unit-test:
    executor: my-custom-executor
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}-<< pipeline.id >>
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-build-<< pipeline.id >>
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test:ci
          environment:
            - JEST_JUNIT_OUTPUT_FILE: "reports/junit/junit.xml"
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit/
  unit-test-badge:
    executor: my-custom-executor
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}-<< pipeline.id >>
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-build-<< pipeline.id >>
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test:cov-and-badge
      - save_cache:
          paths:
            - ~/tmp/badges
          key: node-{{ .Branch }}-branches-<< pipeline.id >>
  int-test:
    executor: my-custom-executor
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}-<< pipeline.id >>
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-build-<< pipeline.id >>
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test:ci:int
          environment:
            - JEST_JUNIT_OUTPUT_FILE: "reports/junit/junit.xml"
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit/
  bench-test:
    executor: my-custom-executor
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}-<< pipeline.id >>
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-build-<< pipeline.id >>
      - run:
          name: Run tests with JUnit as reporter
          command: npm run test:ci:bench
          environment:
            - JEST_JUNIT_OUTPUT_FILE: "reports/junit/junit.xml"
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit/
  publish:
    executor: my-custom-executor
    working_directory: ~/tmp
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}-<< pipeline.id >>
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-{{ .Branch }}-build-<< pipeline.id >>
      - restore_cache:
          keys:
            # used to pull in the badge update
            - node-{{ .Branch }}-branches-<< pipeline.id >>
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish package (pack run only)
          command: npm pack
      - run:
          name: release
          command: CI=false npx semantic-release
# Orchestrate our job run sequence
workflows:
  build_lint_test_publish:
    jobs:
      - build
      - lint:
          requires:
            - build
      - unit-test:
          requires:
            - lint
            - build
      - int-test:
          requires:
            - unit-test
      - bench-test:
          requires:
            - int-test
      - unit-test-badge:
          requires:
            - unit-test
          filters:
            branches:
              only: main
      - publish:
          requires:
            - int-test
            - unit-test-badge
            - bench-test
          filters:
            branches:
              only: main
